[phases.setup]
nixPkgs = ["python311", "pip"]

[phases.install]
cmds = ["python -m pip install --upgrade pip", "python -m pip install ."]

[start]
cmd = "gunicorn --bind 0.0.0.0:$PORT --workers 2 --timeout 120 app:app"
